development:
  twitter:
    key: 1V9lty4RBVlA0E5TObJFw
    secret: IBZgFxmzVQltxhg4wIYhv4F4IHrdvMhLdBplSvuj5lc
production:
  twitter:
    key: RW4KqKih7fkw9N59GpffLg
    secret: KbEsl5rBJSFbIgMDgM0zXuvnN7qoJDPENe9DK2pZhAY